; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro_micro_nrf52840]
platform = https://github.com/LeeorNahum/platform-n-able-pro-micro-nrf52840.git#master
board = pro_micro_nrf52840
framework = arduino
upload_protocol = nrfutil
upload_port = COM7
monitor_port = COM8
monitor_speed = 115200

# UF2 bootloader configuration for Adafruit nRF52 Bootloader
board_build.uf2_family_id = 0xADA52840
board_upload.offset_address = 0x26000
board_upload.maximum_size = 815104

lib_deps =
  https://github.com/h2zero/NimBLE-Arduino.git#master
  adafruit/DHT sensor library @ ^1.4.4
  adafruit/Adafruit Unified Sensor @ ^1.1.14